# apiVersion: helm.toolkit.fluxcd.io/v2beta1
# kind: HelmRelease
# metadata:
#   name: przyrodniczy
#   namespace: default
# spec:
#   interval: 1m
#   chart:
#     spec:
#       chart: ./basic
#       sourceRef:
#         kind: GitRepository
#         name: basic-chart
#         namespace: default
#       interval: 1m
#   values:
#     application:
#       type: wordpress
#       createdb: true
#     replicaCount: 2
#     image:
#       repository: devkrolikowski/wordpress-generic
#       tag: 0.0.1 # {"$imagepolicy": "flux-system:przyrodniczy:tag"}
#     resources:
#       limits:
#         memory: "512Mi"
#         cpu: "500m"
#       requests:
#         memory: "150Mi"
#         cpu: "200m"
#     service:
#       type: ClusterIP
#       port: 80
#     ingress:
#       enabled: true
#       hosts:
#         - host: przyrodniczy.website
#     volumes:
#       enabled: true
#       type:
#         nfs:
#           server: "192.168.3.2"
#           path: "/storage"
#           readOnly: false
#     database:
#       enabled: true
#       server: "192.168.3.2"
