apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: swa
  namespace: default
spec:
  interval: 1m
  chart:
    spec:
      chart: ./basic
      sourceRef:
        kind: GitRepository
        name: basic-chart
        namespace: default
      interval: 1m
  values:
    application:
      type: other
    replicaCount: 1
    image:
      repository: devkrolikowski/swiss-army-knife
      tag: 0.3.0 # {"$imagepolicy": "flux-system:swa:tag"}
    resources:
      limits:
        memory: "50Mi"
        cpu: "50m"
      requests:
        memory: "10Mi"
        cpu: "10m"
    service:
      type: ClusterIP
      port: 80
    ingress:
      enabled: false
