apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: testapp
  namespace: default
spec:
  values:
    application:
      type: other
    replicaCount: 2
    image:
      repository: devkrolikowski/sample-app
      tag: 2.2.1 # {"$imagepolicy": "flux-system:testapp:tag"}
    ingress:
      hosts:
        - host: testapp.lan
