apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: baseapp
  namespace: default
spec:
  interval: 1m
  chart:
    spec:
      chart: ./basic
      sourceRef:
        kind: GitRepository
        name: basic-chart
        namespace: default
      interval: 1m
  values:
    appName: baseapp
    service:
      type: ClusterIP
      port: 80
    ingress:
      enabled: true