apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: testapp
  namespace: default
spec:
  interval: 1m
  chart:
    spec:
      chart: ./basic
      version: '0.1.2'
      sourceRef:
        kind: GitRepository
        name: basic-chart
        namespace: flux-system
      interval: 1m
  values:
    appName: testapp
    replicaCount: 2
    image:
      repository: devkrolikowski/sample-app
      tag: 0.4.1 # {"$imagepolicy": "flux-system:testapp"}
    service:
      type: ClusterIP
      port: 80
    ingress:
      enabled: true
      hosts:
        - host: testapp.lan