apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: demo-app
  namespace: default
spec:
  interval: 1m
  chart:
    spec:
      chart: ./basic
      sourceRef:
        kind: GitRepository
        name: basic-chart
        namespace: default
      interval: 1m
  values:
    application:
      name: demo-app
      type: other
    replicaCount: 2
    image:
      repository: devkrolikowski/demo_app
      tag: 0.1.3 # {"$imagepolicy": "flux-system:demo-app:tag"}
    resources:
      limits:
        memory: "50Mi"
        cpu: "50m"
      requests:
        memory: "10Mi"
        cpu: "10m"
    service:
      type: ClusterIP
      port: 80
    ingress:
      enabled: true
      tls: false
      hosts:
        - host: demo-app.lan
