# apiVersion: helm.toolkit.fluxcd.io/v2beta1
# kind: HelmRelease
# metadata:
#   name: homer
#   namespace: default
# spec:
#   interval: 1m
#   chart:
#     spec:
#       chart: ./basic
#       sourceRef:
#         kind: GitRepository
#         name: basic-chart
#         namespace: default
#       interval: 1m
#   values:
#     application:
#       type: other
#     replicaCount: 1
#     image:
#       repository: b4bz/homer
#       tag: v23.02.2
#     resources:
#       limits:
#         memory: "512Mi"
#         cpu: "600m"
#       requests:
#         memory: "50Mi"
#         cpu: "10m"
#     service:
#       port: 8080
#     ingress:
#       enabled: true
#       hosts:
#         - host: homer.lan
#     volumes:
#       enabled: true
#       mountPath: /www/assets
#       fsuid: 1000
#       fsgid: 1000
#       type:
#         nfs:
#           server: "192.168.3.2"
#           path: "/storage"
#           readOnly: false
